/// <reference types="Cypress" />

describe('logs in to GOAT', () => {
    beforeEach(() => {    
       cy.visit('https://test-goat.tekkon.com.np/admin/login')
       cy.get('#email').and('have.attr', 'placeholder', 'E-mail').type('admin@admin.com')
       cy.get('#password').and('have.attr', 'placeholder', 'Password').type('#t3k@d2021*')
       cy.get('.signin').contains('Login').click()

       
       cy.get('span.hamburger-inner')
        .should('exist')
        .should('have.class', 'hamburger-inner')
        .click()

       cy.get('.title').contains('Device Management').click()
       
       cy.get('.title').contains('My Device Request').click()
       
     })

     it('Makes New Request', () => {
        cy.contains('span','Make new request').click()

        cy.get('input#title')
        .should('exist')
        .should('have.class', 'form-control')
        .should('have.attr', 'name', 'title')
        .type('Dell SE2422H 24 inch Full HD VA Monitor')


        cy.get('.select2-selection__arrow').and('have.attr', 'role','presentation').click()

        cy.contains('li', 'Monitor').click()
        
        cy.get('textarea[name="purpose"]')
        .should('exist')
        .and('have.attr', 'placeholder', 'Purpose')
        .type('Used to display images, text, video, and graphics information generated by a connected computer via a computers video card. ')
        
        
        cy.get('textarea[name="remark"]')
        .should('exist')
        .and('have.attr', 'placeholder', 'Remark')
        .type('24-inch monitor with 1080p resolution or a 27-inch monitor with 1440p resolution')
        
        cy.get('.save').contains('Create').click()
     })

   













    })